# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-QvLMiEVM_QdP-g2ESKYUfm03PtOZg2J
"""

text = input()
length = len(text)
if length < 2:
    print("чудовищно мало")
elif length < 5:
    print("очень мало")
elif length < 10:
    print("мало")
elif length < 30:
    print("ок")
elif length < 100:
    print("много")
else:
    print("чудовищно много")